Add Planar move plugin
ros-ukraine/leobot pull request #138
Opened 2018-12-24 18:42 UTC by SystemDiagnosticss

Add Planar move plugin for mecanum wheels simulated

2018-12-24 21:41 UTC, SystemDiagnosticss commented
https://youtu.be/Lo1OUz-_Y0g

2018-12-26 20:36 UTC, AndriyPt requested changes

2018-12-26 20:36 UTC, AndriyPt commented on leobot_gazebo/package.xml
> +
please remove unneeded line

2018-12-26 20:36 UTC, AndriyPt commented on leobot_description/robot/leobot.gazebo.xacro
> +      <commandTopic>/wheel_diff_drive_controller/cmd_vel</commandTopic>
there topic are not needed. The only control topic is specified here https://github.com/ros-ukraine/leobot/blob/kinetic-devel/leobot_control/launch/control.launch#L11
Please read more about http://wiki.ros.org/twist_mux to find out how it works

2018-12-26 20:36 UTC, AndriyPt commented on leobot_description/robot/leobot.gazebo.xacro
> +      <robotBaseFrame>FL_wheel_link</robotBaseFrame>
Please created dummy link which will slide on the ground and use it as robot base frame. Check this example https://github.com/KristofRobot/frobo/blob/master/frobo_description/urdf/base.urdf.xacro#L200-L213

2019-02-05 00:07 UTC, AndriyPt commented
Closing PR since Planar Plugin was added to kinetic-devel

2019-02-05 00:07 UTC, closed without merging