Initial commit
ros-ukraine/leobot pull request #23
Opened 2018-01-09 15:01 UTC by YarynaD

2018-01-09 16:11 UTC, LyubomyrD approved these changes
Nice work.

2018-01-09 21:26 UTC, AndriyPt requested changes
Good work @YarynaD . I have added a few small remarks. Please fix them and I am happy to merge this PR

2018-01-09 21:26 UTC, AndriyPt commented on docs/design/management/Leobot_html/.gitignore
> +.idea
@YarynaD this file should not be needed since top level .gitignore has *.idea* in the list

2018-01-09 21:26 UTC, AndriyPt commented on docs/design/management/Leobot_html/style.css
> +/*.small-control-panel-button {
please remove commented statements

2018-01-09 21:26 UTC, AndriyPt commented on docs/design/management/Leobot_html/index.html
> +            <button class="control-panel-button">FORWARD</button>
it is hard to see that button is pressed. There is no change of the state of the button during left mouse click. Please change e.g. colour to darker to reflect pressing.

2018-01-17 23:42 UTC, YarynaD commented
Hello @AndriyPt! 
I'm very sorry for such a delay! I finally committed changes. Please, check if I understood everything correct. If you'll suggest further changes, I'll be glad to implement them.

2018-01-19 20:26 UTC, AndriyPt approved these changes

2018-01-19 20:26 UTC, merged

2018-01-19 20:27 UTC, AndriyPt commented
@YarynaD thank you very much for contribution :+1: Merged :)

2018-01-19 23:18 UTC, YarynaD commented
@AndriyPt  thank you very much! It was an interesting task. Hope I'll be able to do something useful for this project in future :)