LeoBotUrdf
ros-ukraine/leobot pull request #36
Opened 2018-02-06 09:13 UTC by LyubomyrD

**Commit Summary:**

Added two standard wheels
Added one caster wheel

2018-02-06 09:58 UTC, AndriyPt requested changes
Few remarks

2018-02-06 09:58 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +       <!-- Leo_left_wheel -->
I guess comment left wheel for link with name left_wheel_link is redundant :)

2018-02-06 09:58 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +    <link name="left_wheel_link">
Please fix XML formatting

2018-02-06 09:58 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +      <xacro:red_material/>
In Gazebo you are using White colour in URDF Red. It might mislead people. Please use one colour for links in Gazebo and URDF :)

2018-02-06 09:58 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +
Please remove extra empty lines

2018-02-06 09:58 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +    <origin rpy="1.570795 0 0" xyz="0.0 0.275 -0.55"/>
Pi is predefined constant. Please use XACRO expressions to calculate 90 degrees as here http://wiki.ros.org/xacro#Math_expressions

2018-02-06 10:31 UTC, LyubomyrD commented
@AndriyPt Thank You for comments. It seems that I corrected everything. Have another look, please.

2018-02-06 17:33 UTC, AndriyPt commented
Robot is not stable in Gazebo simulation
![image](https://user-images.githubusercontent.com/10820297/35874181-88f6a92c-0b74-11e8-8a7e-73758036dd07.png)

2018-02-06 17:34 UTC, AndriyPt requested changes

2018-02-06 17:34 UTC, AndriyPt commented on leobot_description/robot/leobot.gazebo.xacro
> +
Please remove not needed empty lines

2018-02-06 17:34 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +
Please remove not needed empty lines

2018-02-06 17:35 UTC, AndriyPt commented
@LyubomyrD description should be "Closing #<issue number>"

2018-02-06 20:33 UTC, AndriyPt commented
@LyubomyrD please also add transmission as it is done here https://github.com/AndriyPt/ros-navigation-examples/blob/kinetic-devel/moon_description/urdf/wheels.urdf.xacro#L57-L66

2018-02-07 14:54 UTC, LyubomyrD commented
@AndriyPt Thank You for You comments. 

I want to discuss the falling robot issue. 

I guess, that the easiest way is to increase the mass of the caster wheel. But I suggest doing this after @SystemDiagnosticss will finish the head of the robot. The robot is rather tall and all additional mass may cause the instability. 

Another option is that @SystemDiagnosticss set the head weight as almost zero, hence it will not have much influence on the stability of our "pendulum".

What do You think?

2018-02-07 16:32 UTC, AndriyPt commented
@LyubomyrD you could add wider platform on the bottom to hold the wheels and add extra stability. It might be cylinder with bigger radius.

2018-02-07 20:54 UTC, AndriyPt commented
@LyubomyrD I have merged @SystemDiagnosticss `head_link` to trunk. Please resolve URDF conflicts. Please let me know if you need assistance with that :)

2018-02-08 19:45 UTC, AndriyPt commented
PR looks really good.
The only remark is please return TF to RVIz configuration and happy to merge :)
![image](https://user-images.githubusercontent.com/10820297/35994513-51692498-0d19-11e8-8845-ac85b7d18663.png)

2018-02-08 19:58 UTC, AndriyPt approved these changes

2018-02-08 19:59 UTC, merged