Сreate urdf for stereo camera rotation
ros-ukraine/leobot pull request #40
Opened 2018-02-06 11:09 UTC by SystemDiagnosticss

Сreate urdf for stereo camera rotation

2018-02-06 17:58 UTC, AndriyPt commented
"Eyes" are floating in the air but should be on the "head" 
![image](https://user-images.githubusercontent.com/10820297/35875483-16852680-0b78-11e8-86f7-3136b00fd12c.png)

2018-02-06 20:29 UTC, AndriyPt commented
@SystemDiagnosticss please also add `head_link` to Gazebo configuration. The same way as `base_link` was added here https://github.com/ros-ukraine/leobot/blob/kinetic-devel/leobot_description/robot/leobot.gazebo.xacro#L13-L19

2018-02-06 21:27 UTC, SystemDiagnosticss commented
Done

2018-02-07 19:25 UTC, AndriyPt commented
@SystemDiagnosticss from Gazebo I am getting this warning
```[ WARN] [1518031419.419065884, 0.396000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'head_link_joint'.
``` 
Please fix it :)

2018-02-07 19:27 UTC, AndriyPt requested changes

2018-02-07 19:27 UTC, AndriyPt commented on leobot_description/robot/robot.urdf.xacro
> +    <dynamics damping="10" friction="1" />
Please remove dynamics for now

2018-02-07 20:51 UTC, AndriyPt approved these changes

2018-02-07 20:53 UTC, merged