F#16 web server
ros-ukraine/leobot pull request #44
Opened 2018-02-09 10:21 UTC by MaxZhaloba

Almost closes #16.

2018-02-09 11:06 UTC, AndriyPt requested changes
Few remarks

2018-02-09 11:06 UTC, AndriyPt commented on README.md
> +This module requires up-to-date system packages and additional rosdep and npm dependencies before running.
Please remove reference to contributing.md. All developers should follow contributing document and not only web server update will require dependencies installation. Else we will end up having these instructions for all new launch modules :)

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/CMakeLists.txt
> +
please check how minimalistic CMakeList.txt could look like https://github.com/AndriyPt/ros-navigation-examples/blob/kinetic-devel/moon_control/CMakeLists.txt

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/index.html
> +            <h1>OPEN SOURCE TELEPRESENSE ROBOT</h1>
Please fix to *TELEPRESENCE*

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/index.html
> +        <p>LEOBOT©2018 Created by SYSTEMDI <br>Developed by Yaryna Demkiv</p>
please fix footnote according to https://github.com/ros-ukraine/leobot/issues/43

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +    background-image: url("http://res.cloudinary.com/dvhn8lvvz/image/upload/v1515331815/site-logo_xrpypd.png");
please download image to images folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +        background-image: url(http://res.cloudinary.com/dvhn8lvvz/image/upload/c_fill,g_west,h_53,w_53/v1515331815/site-logo_xrpypd.png);
please download image to *images* folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +        background-image: url("http://res.cloudinary.com/dvhn8lvvz/image/upload/c_scale,h_30,w_30/a_270/v1515333945/arrow-right-01-256_b40xbs.png");
please download image to *images* folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +        background-image: url("http://res.cloudinary.com/dvhn8lvvz/image/upload/c_scale,h_30,w_30/a_180/v1515333945/arrow-right-01-256_b40xbs.png");
please download image to *images* folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +        background-image: url("http://res.cloudinary.com/dvhn8lvvz/image/upload/c_scale,h_30,w_30/a_0/v1515333945/arrow-right-01-256_b40xbs.png");
please download image to *images* folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/web_content/style.css
> +        background-image: url("http://res.cloudinary.com/dvhn8lvvz/image/upload/c_scale,h_30,w_30/a_90/v1515333945/arrow-right-01-256_b40xbs.png");
please download image to *images* folder and refer it from there

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/scripts/web_server.js
> +const port = 8080; // hard-coded for now
Please note that all code is located in initNode.then callback https://github.com/RethinkRobotics-opensource/rosnodejs_examples/blob/kinetic-devel/scripts/listener.js#L32-L41

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/scripts/web_server.js
> +#!/usr/bin/env nodejs
please use this approach https://github.com/RethinkRobotics-opensource/rosnodejs_examples/blob/kinetic-devel/scripts/listener.js#L43

2018-02-09 11:06 UTC, AndriyPt commented on leobot_web_server/scripts/web_server.js
> +    nh.getParam('port').then((p) => {
please check this example how parameters are read https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/examples/standard.js#L44-L46

2018-02-09 14:47 UTC, MaxZhaloba commented
I've fixed the simple parts of functionality, but it appears that I don't understand some other ones.

Can we please have a chat on the following items:
1. catkin_package instruction in CMakeLists.txt
2. Conditional listener and initNode in JS file
3. Reading of parameters using rosNode.getParam

2018-02-09 19:26 UTC, MaxZhaloba commented
@AndriyPt, I've fixed all current issues. Feel free to review.

2018-02-10 09:05 UTC, AndriyPt commented
@MaxZhaloba Travis CI is failing. Please make sure that all CI servers are green before requesting re-reviewing of the code :)
The error is
```
CMake Error at cmake_install.cmake:133 (file):
  file INSTALL cannot find
  "/home/user/workspace/src/host/home/travis/build/ros-ukraine/leobot/leobot_web_server/scripts/**/*".
```

2018-02-10 11:14 UTC, MaxZhaloba commented
Fixed

2018-02-10 18:53 UTC, AndriyPt approved these changes

2018-02-10 18:54 UTC, merged